// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhYWMhehCBae7yWtjzGOn2x9iqbECYroU',
    appId: '1:611018478587:web:3cbaf002ed6b98b9f0315e',
    messagingSenderId: '611018478587',
    projectId: 'test-efafe',
    authDomain: 'test-efafe.firebaseapp.com',
    storageBucket: 'test-efafe.firebasestorage.app',
    measurementId: 'G-8JZCNR20FT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ4WriFyIa-5UTJ8Cso-tBFIj4IvE3RSE',
    appId: '1:611018478587:android:a46f976439e047c0f0315e',
    messagingSenderId: '611018478587',
    projectId: 'test-efafe',
    storageBucket: 'test-efafe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRju8LkHogcVSGzlezLPzQmeH0F6FLnI4',
    appId: '1:611018478587:ios:af67fdde4afb2920f0315e',
    messagingSenderId: '611018478587',
    projectId: 'test-efafe',
    storageBucket: 'test-efafe.firebasestorage.app',
    iosBundleId: 'com.example.luxeLoft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRju8LkHogcVSGzlezLPzQmeH0F6FLnI4',
    appId: '1:611018478587:ios:af67fdde4afb2920f0315e',
    messagingSenderId: '611018478587',
    projectId: 'test-efafe',
    storageBucket: 'test-efafe.firebasestorage.app',
    iosBundleId: 'com.example.luxeLoft',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhYWMhehCBae7yWtjzGOn2x9iqbECYroU',
    appId: '1:611018478587:web:b3c04f7de0c7f232f0315e',
    messagingSenderId: '611018478587',
    projectId: 'test-efafe',
    authDomain: 'test-efafe.firebaseapp.com',
    storageBucket: 'test-efafe.firebasestorage.app',
    measurementId: 'G-LW7ZVVQJG4',
  );
}
